### ISSUE TITLE
Extract data and add cross filter functionalities

### ISSUE THREAD

**Issue by LarryAsante** [wuruthie/DataVizFinal#1]
Completed:
- Creating an array of objects with relevant fields that represent a unit of observation for our visualization.
- Add cross filter functionalities
- Retrieve min and max date for use in building slider

**Comment by LarryAsante** [comment]
@wuruthie @uzonwike : I have completed this (implementation and testing) and I'll merge it

**Comment by wuruthie** [comment]
I have no problems with the code. On another note, we may want to consider adding more fields to a terrorism_event object.
